# Generated by Django 4.2.1 on 2023-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='deli', max_length=100, verbose_name="supplier's name")),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ['supplier_name'],
            },
        ),
    ]
