# Generated by Django 4.2.1 on 2023-05-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name="product's name")),
                ('product_description', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, upload_to='images/eshop/')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
    ]
