# Generated by Django 4.2.1 on 2023-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name="product's name")),
                ('product_description', models.CharField(max_length=250)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
    ]
